In [2]:
import pandas as pd

In [3]:
# Function to determine paddock status (With Cattle or Empty)
def paddock_status(load, green_mass, paddock_green_masses):
    if load > 0:
        status_load = 1
    else:
        status_load = 0

    if green_mass <= 0:
        status_resource = -1  # Bad condition
    elif green_mass == max(paddock_green_masses):
        status_resource = 1  # Maximum compared to others
    else:
        status_resource = 0  # Otherwise

    return status_load, status_resource

In [4]:
# Sample DataFrame (replace this with your actual DataFrame)
data = {
    'Paddock1_Green_Mass': [10.5, 15.2, 20.1, 18.3, 22.0],
    'Paddock2_Green_Mass': [8.3, 12.7, 18.9, 16.5, 19.8],
    'Paddock3_Green_Mass': [11.9, 14.6, 22.3, 20.5, 23.7],
    'Paddock4_Green_Mass': [9.1, 13.5, 19.8, 17.6, 21.2],
    'Paddock5_Green_Mass': [12.0, 16.8, 0, 19.4, 24.0],
    'Paddock6_Green_Mass': [10.8, -15.25, 20.7, 18.9, 22.5],
    'Paddock7_Green_Mass': [0, 13.8, 19.0, 17.0, 20.8],
    'Paddock1_Load': [0, 0, 0, 0, 0],
    'Paddock2_Load': [0, 0, 0, 0, 0],
    'Paddock3_Load': [0, 0, 0, 0, 60],
    'Paddock4_Load': [0, 0, 0, 60, 0],
    'Paddock5_Load': [0, 0, 60, 0, 0],
    'Paddock6_Load': [0, 60, 0, 0, 0],
    'Paddock7_Load': [60, 0, 0, 0, 0],
    'Temperature': [25.0, 26.0, 13.0, 30.0, 25.25], 
    'Humidity': [80.5, 75.0, 70.0, 80.0, 72.25],
    'Air Pressure': [1025.0, 1085.0, 1012.0, 1015.0, 1015.0],
    'Wind Speed': [22.5, 10.0, 10.0, 25.0, 25.0],
}

df = pd.DataFrame(data)

In [5]:
df

Paddock1_Green_Mass  Paddock2_Green_Mass  Paddock3_Green_Mass  \
0                 10.5                  8.3                 11.9   
1                 15.2                 12.7                 14.6   
2                 20.1                 18.9                 22.3   
3                 18.3                 16.5                 20.5   
4                 22.0                 19.8                 23.7   

   Paddock4_Green_Mass  Paddock5_Green_Mass  Paddock6_Green_Mass  \
0                  9.1                 12.0                10.80   
1                 13.5                 16.8               -15.25   
2                 19.8                  0.0                20.70   
3                 17.6                 19.4                18.90   
4                 21.2                 24.0                22.50   

   Paddock7_Green_Mass  Paddock1_Load  Paddock2_Load  Paddock3_Load  \
0                  0.0              0              0              0   
1                 13.8              0              0              0   
2                 19.0              0              0              0   
3                 17.0              0              0              0   
4                 20.8              0              0             60   

   Paddock4_Load  Paddock5_Load  Paddock6_Load  Paddock7_Load  Temperature  \
0              0              0              0             60        25.00   
1              0              0             60              0        26.00   
2              0             60              0              0        13.00   
3             60              0              0              0        30.00   
4              0              0              0              0        25.25   

   Humidity  Air Pressure  Wind Speed  
0     80.50        1025.0        22.5  
1     75.00        1085.0        10.0  
2     70.00        1012.0        10.0  
3     80.00        1015.0        25.0  
4     72.25        1015.0        25.0

In [6]:
# Iterate through each day
for day in range(len(df)):
    # Extract green masses for each paddock for the current day
    paddock_green_masses = [df[f'Paddock{i}_Green_Mass'].iloc[day] for i in range(1, 8)]
    
    action_needed = False
    # Iterate through each paddock
    for paddock in range(1, 8):
        load_column = f'Paddock{paddock}_Load'
        green_mass_column = f'Paddock{paddock}_Green_Mass'
        status_column = f'Paddock{paddock}_Status'
        
        # Assign status for the paddock
        assess_load, assess_resource = paddock_status(df[load_column].iloc[day], df[green_mass_column].iloc[day], paddock_green_masses)
        if assess_load == 1 and assess_resource == -1: action_needed = True
        df.at[day, status_column] = assess_resource
    
    df.at[day, "Action_Needed"] = int(action_needed)

In [7]:
df

Paddock1_Green_Mass  Paddock2_Green_Mass  Paddock3_Green_Mass  \
0                 10.5                  8.3                 11.9   
1                 15.2                 12.7                 14.6   
2                 20.1                 18.9                 22.3   
3                 18.3                 16.5                 20.5   
4                 22.0                 19.8                 23.7   

   Paddock4_Green_Mass  Paddock5_Green_Mass  Paddock6_Green_Mass  \
0                  9.1                 12.0                10.80   
1                 13.5                 16.8               -15.25   
2                 19.8                  0.0                20.70   
3                 17.6                 19.4                18.90   
4                 21.2                 24.0                22.50   

   Paddock7_Green_Mass  Paddock1_Load  Paddock2_Load  Paddock3_Load  ...  \
0                  0.0              0              0              0  ...   
1                 13.8              0              0              0  ...   
2                 19.0              0              0              0  ...   
3                 17.0              0              0              0  ...   
4                 20.8              0              0             60  ...   

   Air Pressure  Wind Speed  Paddock1_Status  Paddock2_Status  \
0        1025.0        22.5              0.0              0.0   
1        1085.0        10.0              0.0              0.0   
2        1012.0        10.0              0.0              0.0   
3        1015.0        25.0              0.0              0.0   
4        1015.0        25.0              0.0              0.0   

   Paddock3_Status  Paddock4_Status  Paddock5_Status  Paddock6_Status  \
0              0.0              0.0              1.0              0.0   
1              0.0              0.0              1.0             -1.0   
2              1.0              0.0             -1.0              0.0   
3              1.0              0.0              0.0              0.0   
4              0.0              0.0              1.0              0.0   

   Paddock7_Status  Action_Needed  
0             -1.0            1.0  
1              0.0            1.0  
2              0.0            1.0  
3              0.0            0.0  
4              0.0            0.0  

[5 rows x 26 columns]

In [12]:
from sklearn.model_selection import train_test_split

# Features are all columns except 'Action_Needed'
X = df.drop(columns=[f"Paddock{p}_Status" for p in range(1, 8)]+['Action_Needed'])
# Target variables
y = df[[f"Paddock{p}_Status" for p in range(1, 8)] + ['Action_Needed']]
# Split the data into training and testing sets (80% train, 20% test)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [14]:
from sklearn.multioutput import MultiOutputClassifier
from sklearn.ensemble import RandomForestClassifier

# Features are all columns except 'Action_Needed'
X = df.drop(columns=[f"Paddock{p}_Status" for p in range(1, 8)]+['Action_Needed'])

# Target variables
y = df[[f"Paddock{p}_Status" for p in range(1, 8)] + ['Action_Needed']]

# Split the data into training and testing sets (80% train, 20% test)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=2)

# Initialize Random Forest classifier
rf_classifier = RandomForestClassifier(n_estimators=100, random_state=2)

# Wrap the classifier with MultiOutputClassifier
multi_target_classifier = MultiOutputClassifier(rf_classifier, n_jobs=-1)

# Train the classifier
multi_target_classifier.fit(X_train, y_train)

# Predict on the test set
y_pred = multi_target_classifier.predict(X_test)

# Calculate accuracy for each output column
accuracies = {}
for i, column in enumerate(y_test.columns):
    accuracy = accuracy_score(y_test[column], y_pred[:, i])
    accuracies[column] = accuracy

# Print the accuracy for each output column
for column, accuracy in accuracies.items():
    print(f"Accuracy for {column}: {accuracy}")

C:\ProgramData\anaconda3\lib\site-packages\sklearn\utils\validation.py:623: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if not hasattr(array, "sparse") and array.dtypes.apply(is_sparse).any():


Accuracy for Paddock1_Status: 1.0
Accuracy for Paddock2_Status: 1.0
Accuracy for Paddock3_Status: 0.0
Accuracy for Paddock4_Status: 1.0
Accuracy for Paddock5_Status: 0.0
Accuracy for Paddock6_Status: 1.0
Accuracy for Paddock7_Status: 1.0
Accuracy for Action_Needed: 0.0


In [15]:
test_data = {
    'Paddock1_Green_Mass': [15.5, 18.2, 25.7],
    'Paddock2_Green_Mass': [9.8, 13.4, 17.9],
    'Paddock3_Green_Mass': [10.9, 15.6, 19.3],
    'Paddock4_Green_Mass': [8.5, 12.0, 16.7],
    'Paddock5_Green_Mass': [11.5, 16.2, -25.9],
    'Paddock6_Green_Mass': [13.0, -19.5, 22.3],
    'Paddock7_Green_Mass': [-18.2, 15.8, 19.6],
    'Paddock1_Load': [0, 0, 0],
    'Paddock2_Load': [0, 0, 0],
    'Paddock3_Load': [0, 0, 0],
    'Paddock4_Load': [0, 0, 0],
    'Paddock5_Load': [60, 0, 0],
    'Paddock6_Load': [60, 0, 0],
    'Paddock7_Load': [0, 0, 60],
    'Temperature': [24.5, 25.0, 26.0], 
    'Humidity': [78.0, 75.5, 72.0],
    'Air Pressure': [1020.0, 1022.0, 1023.0],
    'Wind Speed': [20.0, 15.0, 10.0],
}

# Create the DataFrame
test_df = pd.DataFrame(test_data)

# Display the dummy test DataFrame
test_df

Paddock1_Green_Mass  Paddock2_Green_Mass  Paddock3_Green_Mass  \
0                 15.5                  9.8                 10.9   
1                 18.2                 13.4                 15.6   
2                 25.7                 17.9                 19.3   

   Paddock4_Green_Mass  Paddock5_Green_Mass  Paddock6_Green_Mass  \
0                  8.5                 11.5                 13.0   
1                 12.0                 16.2                -19.5   
2                 16.7                -25.9                 22.3   

   Paddock7_Green_Mass  Paddock1_Load  Paddock2_Load  Paddock3_Load  \
0                -18.2              0              0              0   
1                 15.8              0              0              0   
2                 19.6              0              0              0   

   Paddock4_Load  Paddock5_Load  Paddock6_Load  Paddock7_Load  Temperature  \
0              0             60             60              0         24.5   
1              0              0              0              0         25.0   
2              0              0              0             60         26.0   

   Humidity  Air Pressure  Wind Speed  
0      78.0        1020.0        20.0  
1      75.5        1022.0        15.0  
2      72.0        1023.0        10.0

In [16]:
# Predict on the test data
y_pred_test = multi_target_classifier.predict(test_df)

In [17]:
y_pred_test

array([[0., 0., 0., 0., 1., 0., 0., 1.],
       [0., 0., 0., 0., 1., 0., 0., 1.],
       [0., 0., 0., 0., 1., 0., 0., 0.]])

In [32]:
import numpy as np
from sklearn.datasets import make_multilabel_classification
from sklearn.multioutput import MultiOutputClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split

# Generate multilabel classification data
X, y_multiclass = make_multilabel_classification(n_classes=3, n_labels=2, random_state=0)
y_binary = np.random.randint(2, size=(X.shape[0], 1))  # Generate binary labels

# Combine binary and multiclass labels
y = np.hstack((y_binary, y_multiclass))

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Initialize MultiOutputClassifier with suitable base estimator
base_estimator = LogisticRegression()  # You can use any classifier as the base estimator
clf = MultiOutputClassifier(base_estimator)

# Fit the classifier to the training data
clf.fit(X_train, y_train)

# Predict on the test data
y_pred = clf.predict(X_test)

# Print the predictions
print("Predictions on test data:")
print(y_pred)

Predictions on test data:
[[0 0 1 1]
 [1 0 0 1]
 [1 0 0 1]
 [0 1 1 1]
 [0 0 1 0]
 [1 1 1 1]
 [0 1 1 0]
 [1 1 1 0]
 [1 1 0 1]
 [0 0 1 0]
 [1 1 0 1]
 [1 1 0 1]
 [0 0 1 1]
 [1 0 0 0]
 [1 1 1 1]
 [1 1 1 0]
 [0 1 1 1]
 [0 1 0 1]
 [0 1 1 1]
 [0 0 1 1]]


In [33]:
import pandas as pd

In [34]:
# Function to apply conditions and create 'State' column
def get_state(row):
    if row['Resource'] <= 0 and row['Load'] != 0:
        return 0
    elif row['Resource'] > 0 and row['Load'] != 0:
        return 1
    elif row['Resource'] <= 0 and row['Load'] == 0:
        return 2
    elif row['Resource'] >= 0 and row['Load'] == 0:
        return 3

In [35]:
# Sample DataFrame
data = {'Resource': [-1.5, 0.0, 2.0, -3.0, 1.0],
        'Load': [3, 0, 5, 2, 0]}

df = pd.DataFrame(data)
df

Resource  Load
0      -1.5     3
1       0.0     0
2       2.0     5
3      -3.0     2
4       1.0     0

In [36]:
# Apply the function to create the 'State' column
df['State'] = df.apply(get_state, axis=1)
df

Resource  Load  State
0      -1.5     3      0
1       0.0     0      2
2       2.0     5      1
3      -3.0     2      0
4       1.0     0      3